// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://njnyoiojvbgzbzgnvuxt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5qbnlvaW9qdmJnemJ6Z252dXh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMjA0MzYsImV4cCI6MjA3MTg5NjQzNn0.ich7gZ83cf_6rwt5dz5sefQu2wEOwBuguXj8Qq6XvjY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});